"""
Configuration file generator for PTO testing framework.

Generates kernel_config.py files compatible with simpler's CodeRunner.
"""

from pathlib import Path
from typing import Any, Dict, List


class ConfigGenerator:
    """Generates kernel_config.py for simpler runtime.

    The generated config file defines:
    - KERNELS: List of kernel configurations with func_id, source, core_type
    - ORCHESTRATION: Dict with source path and function name

    Example output:
        from pathlib import Path

        _KERNELS_ROOT = Path(__file__).parent

        ORCHESTRATION = {
            "source": str(_KERNELS_ROOT / "orchestration" / "orch.cpp"),
            "function_name": "build_test_graph",
        }

        KERNELS = [
            {"func_id": 0, "source": str(_KERNELS_ROOT / "aiv" / "func.cpp"), "core_type": "aiv"},
        ]
    """

    def generate(
        self,
        kernels_dir: Path,
        kernel_configs: List[Dict[str, Any]],
        orch_source: str, 
        orch_function_name: str = "build_test_graph",
    ) -> str:
        """Generate kernel_config.py content.

        Args:
            kernels_dir: Base directory for kernels (used for relative paths).
            kernel_configs: Kernel config dicts from KernelGenerator.
            orch_source: Path to orchestration source file.
            orch_function_name: Name of orchestration function.

        Returns:
            Python source code for kernel_config.py.
        """
        kernels_dir = Path(kernels_dir)
        orch_path = Path(orch_source)

        # Compute relative path for orchestration
        try:
            orch_rel = orch_path.relative_to(kernels_dir)
        except ValueError:
            # Not relative, use just the filename in expected location
            orch_rel = Path("orchestration") / orch_path.name

        lines = [
            '"""',
            'Auto-generated kernel configuration.',
            '',
            'Generated by pto_test.codegen.ConfigGenerator',
            '"""',
            '',
            'from pathlib import Path',
            '',
            '_KERNELS_ROOT = Path(__file__).parent',
            '',
            'ORCHESTRATION = {',
            f'    "source": str(_KERNELS_ROOT / "{orch_rel.as_posix()}"),',
            f'    "function_name": "{orch_function_name}",',
            '}',
            '',
            'KERNELS = [',
        ]

        for kc in kernel_configs:
            source_path = Path(kc["source"])
            # Compute relative path
            try:
                source_rel = source_path.relative_to(kernels_dir)
            except ValueError:
                # Not relative, use core_type/filename
                source_rel = Path(kc["core_type"]) / source_path.name

            lines.append(
                f'    {{"func_id": {kc["func_id"]}, '
                f'"source": str(_KERNELS_ROOT / "{source_rel.as_posix()}"), '
                f'"core_type": "{kc["core_type"]}"}},'
            )

        lines.append(']')
        lines.append('')

        return '\n'.join(lines)

    def write(
        self,
        kernels_dir: Path,
        kernel_configs: List[Dict[str, Any]],
        orch_source: str,
        orch_function_name: str = "build_test_graph",
    ) -> Path:
        """Generate and write kernel_config.py to kernels directory.

        Args:
            kernels_dir: Directory to write kernel_config.py into.
            kernel_configs: Kernel config dicts from KernelGenerator.
            orch_source: Path to orchestration source file.
            orch_function_name: Name of orchestration function.

        Returns:
            Path to the written kernel_config.py file.
        """
        content = self.generate(kernels_dir, kernel_configs, orch_source, orch_function_name)
        config_path = Path(kernels_dir) / "kernel_config.py"
        config_path.write_text(content)
        return config_path
